name: golangci-lint

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: goversion
        run: |
          cat Dockerfile | awk '/^FROM golang:.* AS builder$/ {v=$2;split(v,a,":");split(a[2],b,"-")}; END {printf("version=%s", b[1])}' >> $GITHUB_OUTPUT
      - uses: actions/setup-go@v5
        with:
          go-version: "${{ steps.goversion.outputs.version }}"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
